#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg}

readonly log_facility="${service}"
. ${scripts_base}/common

if [ -z "$(which make)" -o -z "$(which wget)" -o -z "$(which file)" ]; then
   readonly log_file=${service_log}
   log "${critical} Build environment not ready"
   ${scripts_base}/install_build_env ||  exit 14
else
    readonly log_file=${build_log}
   log "${success} Build environment ready"
   exit 0
fi
