#!/bin/bash

readonly scripts_cfg=${0%/scripts*}/etc/scripts.cfg

. ${scripts_cfg}
readonly log_file=${service_log}
readonly log_facility="${service}"
. ${scripts_base}/common

if [ -z "$(which make)" ]; then
   log "${critical} Build environment not ready"
   exit 3
else
   log "${success} Build environment ready"
   exit 0
fi