#!/bin/bash

readonly docker_cfg=${0%/scripts*}/etc/docker.cfg
readonly scripts_cfg=${0%/scripts*}/etc/scripts.cfg

. ${scripts_cfg}

if [ ! -f ${docker_cfg} ];then
    echo "Docker config ${docker_cfg} not found"
    exit 3
fi

. ${docker_cfg}

readonly docker_run=${service_root}/data/run/docker
readonly hash_file=${docker_run}/${container}
readonly log_file=${service_root}/log/service.log
readonly log_facility="${service}"

. ${scripts_base}/common

case "$1" in
    "start")
	log "${info} Docker container start"
	if [ ! -d ${docker_run} ]; then
	    mkdir -p ${docker_run}
	fi
	hash=$(docker run ${docker_mounts} ${docker_ports} --name ${container} -d -t ${image} ${container_init} )
	if [ -n ${hash} ]; then
	    echo ${hash} > ${hash_file}
	    log "${success} Container ${container} (${hash}) started"
	else
	    log "${critical} Problem starting ${container}"
	    exit 2
	fi
	;;
    "stop")
	hash=$(cat ${hash_file})
	if [ -n "${hash}" ]; then
	    log "${info} Stopping ${hash}..."
	    docker stop -t=15 ${hash}
	    docker rm ${hash}
	    log "${success} Stopped"
	else
	    log "${critical} hashfile ${hash_file} not found"
	    exit 2
		fi
	;;
    *)
	echo "Syntax: $0 [start|stop]"
esac
exit 0
