#!/bin/bash

readonly scripts_cfg=${0%/scripts*}/etc/scripts.cfg

. ${scripts_cfg} 

readonly log_file=${service_log}
readonly module="cron"
readonly log_facility="${service}-${module}"
readonly daemon=/usr/sbin/cron
readonly pidfile=${run_dir}/${module}.pid

. ${scripts_base}/common


case "$1" in
	"start")
		log "${info} Starting ${module}"
		${daemon} &
		echo $! > ${pidfile}

		log "${success} ${module} started"
	;;
	"stop")
	        log "${info} Stopping ${module}..."
		readonly pid=$(cat ${pidfile})
	        kill ${pid}
		waited=0
		while [ -n "$(ps -o pid= -o comm= -p ${pid} )" ]; do
		    waited=$(( waited + 1 ))
		    if [ ${waited} -gt 15 ]; then
			kill -9 ${pid}
			break
		    fi
		    sleep 1
		done
		log "${success} Stopped"

	;;
	*)
		echo "Syntax: $0 [start|stop]"
esac
exit 0
