#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 

readonly log_file=${service_log}
readonly module="cron"
readonly log_facility="${service}-${module}"
readonly daemon=/usr/sbin/cron
readonly pidfile=${run_dir}/${module}.pid

. ${scripts_base}/common

case "$1" in
    "start")
	log "${info} Starting ${module}"
	if [ ! -f ${daemon} ]; then
            ${scripts_base}/build/cron
    	fi
	
	daemon_start ${daemon} " " ${pidfile}
	;;

	"stop")
	daemon_stop ${pidfile}
	;;

	*)
	echo "Syntax: $0 [start|stop]"
esac
exit 0
