#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 

readonly log_file=${service_log}
readonly module="cron"
readonly log_facility="${service}-${module}"
readonly daemon=/usr/sbin/cron
readonly pidfile=${run_dir}/${module}.pid

. ${scripts_base}/common

case "$1" in
	"start")
		log "${info} Starting ${module}"
		if [ ! -f ${daemon} ]; then
        		${scripts_base}/build/cron
    		fi

		if is_running ${module} ; then
		    log "${warning} ${module} already running"
		else
		    ${daemon} &
		    echo $! > ${pidfile}
		fi
		log "${success} ${module} started"
	;;
	"stop")
	        log "${info} Stopping ${module}..."
		daemon_stop ${pidfile}
		log "${success} Stopped"

	;;
	*)
		echo "Syntax: $0 [start|stop]"
esac
exit 0
