#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 

readonly log_file=${service_log}
readonly log_facility="${service}"

. ${scripts_base}/common


if [ ! -h /sbin/initctl ]; then
    # "fix" service startup problem inside docker
    dpkg-divert --local --rename --add /sbin/initctl
    ln -s /bin/true /sbin/initctl
    log "${success} Docker service start fix applied"
fi
