#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 

echo "WARNING: this script has been renamed to docker-service-startup-fix"
${scripts_base}/docker-service-startup-fix
