#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg}
readonly log_file=${service_log}
readonly log_facility="${service}-exim4"
. ${scripts_base}/common

readonly exim4_cfg=update-exim4.conf.conf
readonly service_exim4_dir=${etc_dir}
readonly system_exim4_dir=/etc/exim4

if [ ! -s ${system_exim4_dir}/${exim4_cfg} ]; then 
    ln -s ${service_exim4_dir}/${exim4_cfg} ${system_exim4_dir}
    if [ $? -eq 0 ]; then
	log "${success} ${exim4_cfg} installed"
	if update-exim4.conf ; then
	    log "${success} exim4 reconfigured"
	else
	    log "${critical} Problem reconfiguring exim4"
	fi
    else
	log "${critical} Problem installing ${exim4_cfg}"
    fi
else
    log "${warning} ${exim4_cfg} already installed"
fi
