#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 

readonly log_file=${service_log}
readonly module="glassfish"
readonly log_facility="${service}-${module}"
readonly daemon=${usr_prefix}/glassfish/bin/asadmin

. ${scripts_base}/common

glassfish_start(){
    log "${info} Starting ${module}"

    # jdk should have been installed with glassfish...

    # if [ -z "${gfadmin_port}" -o -z "${gfdeployer_password_file} ]

    if [ ! -f ${daemon} -o ! -d ${usr_prefix}/glassfish/glassfish/domains/domain1 ]; then
	log "${info} Installing Glassfish"
	${scripts_base}/build/glassfish
	# log "${info} Deploying war"
	# ${usr_prefix}/glassfish/bin/asadmin --port ${gfadmin_port} --passwordfile ${gfdeployer_password_file} deploy ${data_dir}/war/stable/3dembenchmark.war | logalize ${build_log}	
    else
	log "${info} Starting domain1"
	${daemon} start-domain domain1
    fi

    log_status $? "${module} started" "Problem starting ${module}"
}

glassfish_stop(){
    log "${info} Stopping ${module}..."
    ${daemon} stop-domain domain1
    log_status $? "${module} Stopped" "Problem stoppping ${module}"
}

case "$1" in
    "start")
	glassfish_start
	;;
    "stop")
	glassfish_stop
	;;
    "restart")
	glassfish_stop
	glassfish_start
	;;
    *)
	echo "Syntax: $0 [start|stop|restart]"
esac

exit 0
