#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 

readonly log_file=${service_log}
readonly module="glassfish"
readonly log_facility="${service}-${module}"
readonly daemon=${usr_prefix}/glassfish/bin/asadmin

. ${scripts_base}/common

glassfish_start(){
    log "${info} Starting ${module}"

    if [ ! -f ${daemon} ]; then
	log "${info} Installing Glassfish"
	${scripts_base}/build/glassfish
    fi

    ${daemon} start-domain domain1
    log_status $? "${module} started" "Problem starting ${module}"
}

glassfish_stop(){
    log "${info} Stopping ${module}..."
    ${daemon} stop-domain domain1
    log_status $? "${module} Stopped" "Problem stoppping ${module}"
}

case "$1" in
    "start")
	glassfish_start
	;;
    "stop")
	glassfish_stop
	;;
    "restart")
	glassfish_stop
	glassfish_start
	;;
    *)
	echo "Syntax: $0 [start|stop|restart]"
esac

exit 0
