#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 

readonly log_file=${service_log}
readonly module="guacamole"
readonly log_facility="${service}-${module}"
readonly daemon=${usr_prefix}/guacamole-server/sbin/guacd
readonly pidfile=${run_dir}/${module}.pid
. ${scripts_base}/common


service_start(){
    log "${info} Starting ${module}"
    ${daemon} -p ${pidfile}
    status=$? ; pid=$!
    if [ ${status} -eq 0 ]; then
	# echo ${pid} > ${pidfile}
	log "${success} ${daemon} started"
    else
	log "${critical} Problem starting ${daemon}"
    fi
}

service_stop(){
    log "${info} Stopping ${module}..."
    daemon_stop ${pidfile}
    log "${success} Stopped"
}

case "$1" in
    "start")
	service_start
	;;
    "stop")
	service_stop
	;;
    "restart")
	service_stop
	service_start
	;;
    *)
	echo "Syntax: $0 [start|stop|restart]"
esac

exit 0
