#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 
. ${scripts_base}/common

# by default, change the password only if at least
# 7 days passed since last change
readonly change_frequency=604800
readonly log_file=${log_dir}/service.log
readonly log_facility="guac-chpass"
readonly plain_db=${etc_dir}/rdp-user.txt
readonly berkeley_db=${etc_dir}/rdp-user.db

if [ ! -f ${etc_dir}/guacamole/last-passwd-change ]; then
    readonly last_change=0
else
    readonly last_change=$(cat ${etc_dir}/guacamole/last-passwd-change)
fi

readonly now=$(date +%s)
readonly seconds_since_last_change=$(( now - last_change))


guacamole_user="scipion"
os_user=${guacamole_user}
force_change=0

while getopts "g:o:hf" options; do
    case "${options}" in
        g)
	    guacamole_user="${OPTARG}"
	    ;;
        o)
	    os_user="${OPTARG}"
	    ;;
	f)
	    force_change=1
	    ;;
	h)
	    echo "Syntax: $0 [-g guacamole_user] [-o os_user] [-f (force)] [-h (help)]"
	    exit 0
	    ;;
    esac
done


log "${info} $0"

# With xrdp, we need to update user-mapping and rdp-user.db

if [ ${seconds_since_last_change} -ge ${change_frequency} -o ${force_change} -eq 1 ]; then 
    # db load command comes from  db5.1-util package (by now)
    which db5.1_load > /dev/null || debian_install db5.1-util

    readonly new_pass=$( random_str )
    readonly regex_guac=$(echo '\(.*\)'${guacamole_user}'" password="\([^"]*\)"')
    readonly regex_os=$(echo '\(.*\)'${os_user}'</param><param name="password">\([^<]*\)</param>')
    # Update guacamole user-mapping: change guacamole pass ("authorize username" line)
    # and its corresponding RDP pass ("param password" line)
    sed -i "s_${regex_guac}_\1${guacamole_user}\" password=\"${new_pass}\"_g" ${etc_dir}/guacamole/user-mapping.xml && sed -i "s_${regex_os}_\1${os_user}</param><param name=\"password\">${new_pass}</param>_g" ${etc_dir}/guacamole/user-mapping.xml && log "${success} Guacamole password updated"
    if [ -f ${plain_db} ] && grep ${os_user} ${plain_db} > /dev/null; then
	tmp_file=$(mktemp)
	# the system user (for RDP) might be different from guacamole user
	awk -v np=${new_pass} -v u=${os_user} '{print $1; if($1 == u){getline;print np}}' < ${plain_db} > ${tmp_file}
	mv ${tmp_file} ${plain_db}
	chown root.root ${plain_db} ${berkeley_db}
	chmod 600 ${plain_db} ${berkeley_db}
	db5.1_load -T -t hash -f ${plain_db} ${berkeley_db}
    else
	echo ${new_pass} | ${scripts_base}/xrdp-user-add ${os_user}
    fi
    date +%s > ${etc_dir}/guacamole/last-passwd-change 
fi
