#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 
. ${scripts_base}/common

# by default, change the password only if at least
# 7 days passed since last change
readonly change_frequency=604800
readonly log_file=${log_dir}/service.log
readonly log_facility="guac-chpass"
readonly plain_db=${etc_dir}/rdp-user.txt
readonly berkeley_db=${etc_dir}/rdp-user.db

if [ ! -f ${etc_dir}/guacamole/last-passwd-change ]; then
    readonly last_change=0
else
    readonly last_change=$(cat ${etc_dir}/guacamole/last-passwd-change)
fi

readonly now=$(date +%s)
readonly seconds_since_last_change=$(( now - last_change))

log "${info} $0"

# !!!! Allow specifying which guacamole account to change pass

# With xrdp, we need to update user-mapping and rdp-user.db

if [ ${seconds_since_last_change} -ge ${change_frequency} ]; then 
    # db load command comes from  db5.1-util package (by now)
    debian_install db5.1-util

    readonly new_pass=$( random_str )
    readonly regex='\(.*\)scipion" password="\([^"]*\)"'
    sed -i "s_${regex}_\1scipion\" password=\"${new_pass}\"_g" ${etc_dir}/guacamole/user-mapping.xml && log "${success} Guacamole password updated"
    if grep scipion ${plain_db} > /dev/null; then
	tmp_file=$(mktemp)
	awk -v np=${new_pass} '{print $1; if($1 == "scipion"){getline;print np}}' < ${plain_db} > ${tmp_file}
	mv ${tmp_file} ${plain_db}
	chown root.root ${plain_db} ${berkeley_db}
	chmod 600 ${plain_db} ${berkeley_db}
	db5.1_load -T -t hash -f ${plain_db} ${berkeley_db}
    else
	echo ${new_pass} | ${scripts_base}/xrdp_user_add scipion
    fi
fi

    date +%s > ${etc_dir}/guacamole/last-passwd-change 
fi
