#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 
. ${scripts_base}/common

# readonly log_file=${log_dir}/service.log
# readonly log_facility="guac-chpass"

if [ $# -lt 1 ]; then
    readonly guser=$(whoami)
else
    readonly guser=${1}    
fi

if grep "${guser}" ${etc_dir}/guacamole/user-mapping.xml > /dev/null; then 
    grep "${guser}" ${etc_dir}/guacamole/user-mapping.xml | grep authorize |  sed 's_.* password="\([^"]*\)".*_\1_g'
else
    echo "User not found"
    exit 1
fi
