#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 
. ${scripts_base}/common

readonly log_file=${log_dir}/service.log
readonly log_facility="guac-chpass"

readonly guacamole_user=${1:-scipion}

grep "${guacamole_user}" ${etc_dir}/guacamole/user-mapping.xml | sed 's_.* password="\([^"]*\)".*_\1_g'

