#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 
. ${scripts_base}/common

# check for sqlite3 availability

[ $# -ne 6 ] && echo "Wrong number of parameters" && exit 2

readonly db=${etc_dir}/sessions.db

echo "INSERT INTO sessions values ('$1','$2','$3','$4','$5','$6');" | sqlite3 ${db}

exit ${PIPESTATUS[1]}

