#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 

readonly log_file=${service_log}
readonly module="guacamole"
readonly log_facility="${service}-${module}"
readonly daemon=${usr_prefix}/guacamole-server/sbin/guacd
readonly pidfile=${run_dir}/${module}.pid
readonly default_address="127.0.0.1"
# possible values: debug, info, warning, error
# @see http://guac-dev.org/doc/0.9.9/gug/configuring-guacamole.html
readonly guacd_log_level="debug"

. ${scripts_base}/common

# dependencies - see guacamole-server installer
spack load --dependencies pkgconf
spack load --dependencies libpng
spack load --dependencies libjpeg-turbo
spack load --dependencies cairo


service_start(){
    log "${info} Starting ${module}"
    ${daemon} -p ${pidfile} -b ${default_address} -l ${guacd_port:-4822} -L ${guacd_log_level}
    status=$? ; pid=$!
    if [ ${status} -eq 0 ]; then
	# echo ${pid} > ${pidfile}
	log "${success} ${daemon} started"
    else
	log "${critical} Problem starting ${daemon}"
    fi
}

service_stop(){
    log "${info} Stopping ${module}..."
    daemon_stop ${pidfile}
    log "${success} Stopped"
}

case "$1" in
    "start")
	service_start
	;;
    "stop")
	service_stop
	;;
    "restart")
	service_stop
	service_start
	;;
    *)
	echo "Syntax: $0 [start|stop|restart]"
esac

exit 0
