#!/bin/bash -e
#
# start/stop the portable service where this script is located
#
### BEGIN INIT INFO
# Provides:          ps
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start a portable service
# Description:       Portable Services (ps-scripts) architecture includes
#                    service_root/etc/service-manager, which actually handles service start
### END INIT INFO

script_path=$0
[ -L $0 ] && script_path="$(readlink -f "$0")"

readonly service_cfg=${script_path%/scripts*}/etc/service.cfg

. ${service_cfg} 
. ${scripts_base}/common

case "$1" in
  start)
	${etc_dir}/service-manager start
      ;;
  stop)
	${etc_dir}/service-manager stop
	;;
  restart)
	${etc_dir}/service-manager stop
	${etc_dir}/service-manager start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
