#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} && . ${scripts_base}/common

log "${info} installing build environment"

apt-get install -y build-essential wget file 2>&1 | logalize ${log_dir}/apt.log

if [ $? -eq 0 ];then
    log "${success} build environment installed"
    status=0
else
    log "${critical} problem installing build environment"
    status=2
fi

exit ${status}
