#!/bin/bash

# Note: this script is intended to be run as the meteor_app_user 

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 

readonly log_file=${log_dir}/django.log
readonly module="meteor"
readonly log_facility="${service}-${module}"
readonly pidfile=${run_dir}/${module}.pid

. ${scripts_base}/common

meteor_start(){
    log "${info} Starting ${module}"

    [ -z "${meteor_app_dir}" ] && log "${critical} Define meteor_app_dir in service.cfg" && exit 7
    [ -z "${ROOT_URL}" ]  && log "${critical} Define ROOT_URL in service.cfg" && exit 7
    [ -z "${meteor_dbname}" ]  && log "${critical} Define meteor_dbname in service.cfg" && exit 7   

    #    if [ -z "$(which node)" ]; then
#	log "${info} Installing node"
#	${scripts_base}/build/node
#   fi

    [ ! -f ${pidfile} ] && touch ${pidfile}
    #chown ${gunicorn_user} ${pidfile}
    [ ! -f ${log_file} ] && touch ${log_file}
    #chown ${gunicorn_user} ${log_file}



    cd ${meteor_app_dir}
    # development mode: enough to run meteor directly
    # meteor run --settings config.json

    # production
    cd programs/server
    ${usr_prefix}/node/bin/npm install --production
    if [ $? -ne 0 ]; then
        log "${critical} Problem with npm install"
        exit 6
    fi
      
    cd ${meteor_app_dir}
    # Mongo environment
    # 'mongodb://user:password@host:port/databasename'
    [ -z "${mongo_host}" ] && readonly mongo_host=localhost
    [ -z "${mongo_port}" ] && readonly mongo_port=27017
    export MONGO_URL="mongodb://${mongo_host}:${mongo_port}/${meteor_dbname}"
    export PORT=${meteor_port:-3000}
    # export MAIL_URL='smtp://user:password@mailhost:port/'
    ${usr_prefix}/node/bin/node main.js --settings ${etc_dir}/config.json
    
    status=$? ; pid=$!
    if [ ${status} -eq 0 ]; then
	echo ${pid} > ${pidfile}
	log "${success} ${module} started"
    else
	log "${critical} Problem starting ${module}"
    fi
}

meteor_stop(){
    log "${info} Stopping ${module}..."
    daemon_stop ${pidfile}
    log "${success} Stopped"
}

case "$1" in
    "start")
	meteor_start
	;;
    "stop")
	meteor_stop
	;;
    "restart")
	meteor_stop
	meteor_start
	;;
    *)
	echo "Syntax: $0 [start|stop|restart]"
esac

exit 0
