#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 

readonly log_file=${service_log}
readonly module="mongodb"
readonly log_facility="${service}-${module}"
readonly mongo_log="${logdir}/mongodb.log"

print_usage(){
    echo "Syntax: $0 [-h] start|stop|restart"
    exit 1
}
# !!!! create script to generate mongodb.conf from service.cfg

readonly pidfile=${run_dir}/${module}.pid
. ${scripts_base}/common

mongodb_start(){
    log "${info} Starting ${module}"

    if [ -z "$(which mongod)" ]; then
	log "${info} Installing mongodb"
	${scripts_base}/build/mongodb
    fi

    [ -z "${mongo_host}" ] && readonly mongo_host=localhost
    [ -z "${mongo_port}" ] && readonly mongo_port=27017

    
    # Set up everything that may be missing
    id mongodb > /dev/null
    if [ $? -ne 0 ]; then
	${scripts_base}/create-user - mongodb ${run_dir}/mongodb /usr/sbin/nologin
    fi

    [ ! -f ${mongo_log} ] && touch ${mongo_log}
    chown mongodb ${mongo_log}
    
    [ -z "${mongodb_path}" ] && readonly mongodb_path=${data_dir}/db
    [ ! -d ${mongodb_path} ] && mkdir ${mongodb_path}
    chown -R mongodb ${mongodb_path}

    # !!!! make --smallfiles configurable (service.cfg)
    # when there is less than 4GB for journaling, smallfiles parameter is needed
    mongod --config /services/scm/etc/mongodb.conf --port ${mongo_port} --bind_ip ${mongo_host} --logappend --logpath ${mongo_log} --pidfilepath ${pidfile} --smallfiles --fork
    if [ $? -eq 0 ]; then
	log "${success} ${daemon} started"
    else
	log "${critical} Problem starting ${daemon}"
    fi
}

mongodb_stop(){
    log "${info} Stopping ${module}..."
    daemon_stop ${pidfile}
    log "${success} Stopped"
}

readonly action=$1
shift
while getopts "h" options; do
    case "${options}" in
	h)
	    print_usage
		;;
        *)
	    echo "Unknow option" 1>&2 
	    print_usage
	    ;;
	
    esac
done

case "${action}" in
    "start")
	mongodb_start 
	;;
    "stop")
	mongodb_stop
	;;
    "restart")
	mongodb_stop
	mongodb_start
	;;
    *)
	echo "Syntax: $0 [start|stop|restart]"
esac

exit 0
