#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 

readonly log_file=${service_log}
readonly module="mysql"
readonly log_facility="${service}-${module}"
readonly mysql_cfg=/etc/mysql/my.cnf
readonly daemon=/usr/sbin/mysqld
readonly pidfile=${run_dir}/${module}.pid

readonly default_mysql_datadir=/var/lib/mysql
readonly mysql_datadir=${data_dir}/mysql
. ${scripts_base}/common


mysql_start(){
    log "${info} Starting ${module}"

    if [ ! -f ${daemon} ]; then
	log "${info} Installing MySQL"
	${scripts_base}/build/mysql
    fi

    if [ -d ${mysql_datadir} ]; then
	if [ ! -h ${default_mysql_datadir} ]; then
	    mv ${default_mysql_datadir} ${default_mysql_datadir}.orig
	    ln -s ${mysql_datadir} ${default_mysql_datadir}
	fi
    else
	log "${critical} MySQL data dir ${mysql_datadir} missing"
	exit 2
    fi

    # !!!! simple check - improve for the case of many mysql daemons running at the same time
    if /etc/init.d/mysql status | grep stopped; then
	daemon_start ${daemon} " " ${pid_file}
    else
	log "${warning} MySQL already started"
    fi
}

mysql_stop(){
    daemon_stop ${pidfile}
}

case "$1" in
    "start")
	mysql_start
	;;
    "stop")
	mysql_stop
	;;
    "restart")
	mysql_stop
	mysql_start
	;;
    *)
	echo "Syntax: $0 [start|stop|restart]"
esac

exit 0
