#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg}
readonly log_file=${service_log}
readonly log_facility="${service}-mysql"
. ${scripts_base}/common

check_params "backup_file" $0 $@

if [ ! $(which mysql) ]; then
    log "${critical} Missing mysql client"
    exit 2
fi

readonly backup_file=$1

if [ ! -f ${backup_file} ]; then
    log "${critical} File ${backup_file} not found"
    exit 2
fi

log "${info} Restoring backup from ${backup_file}"

cat ${backup_file} | mysql

if [ $? -eq 0 ]; then
    log "${success} Backup restored from ${backup_file}"
else
    log "${critical} Problem restoring backup from ${backup_file}"
fi
