#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg}

readonly backup_cfg_dir=${etc_dir}/backup

readonly config_file=${backup_cfg_dir}/main.cfg
readonly exclude_file=${backup_cfg_dir}/exclude.cfg

readonly log_file=${backup_log}
readonly log_facility="${service}-backup"

. ${scripts_base}/common

readonly backup_dir=${data_dir}/mysql-backup
readonly backup_file=${service}-db-backup
[ -z "${mysql_auth_file}" ] && readonly mysql_auth_file=${etc_dir}/mysql.cnf

log "${info} MySQL BACKUP STARTED"

git=$(which git)

if [ -z "${git}" ]; then
    ${scripts_base}/build/git || exit $?
fi

[ -z "${GIT_SSH}" ] && GIT_SSH="${scripts_base}/ssh"

[ -f ${mysql_auth_file} ] && readonly mysql_auth="--defaults-file=${mysql_auth_file}"

[ ! -d ${backup_dir} ] && mkdir -p ${backup_dir}

git=$(which git)

cd ${backup_dir}
mysqldump  ${mysql_auth} --all-databases > ${backup_file}
status=$?

if [ ${status} -eq 0 ]; then
    ${git} add ${backup_file}
    ${git} commit -m "${backup_file} $(date +%s)"
    log "${success} MySQL BACKUP FINISHED"
else
    log "${critical} Error backing up MySQL"
fi
