#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg
. ${service_cfg} 

[ -z "${nagios_cfg}" ] && readonly nagios_cfg=${etc_dir}/nagios/nagios.cfg

${usr_prefix}/nagios/bin/nagios -v ${nagios_cfg}
