#!/bin/bash

# read uid and name from service.cfg
readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} && . ${scripts_base}/common

readonly log_file=${log_dir}/service.log

log "${info} nagios-user"

if grep ${service_user} /etc/group; then
    log "${warning} Group ${service_user} already available"
else
    groupadd -g ${service_gid} ${service_user} 
    log "${info} Group ${service_user} created"
fi

if grep ${service_user} /etc/passwd; then
    log "${warning} User ${service_user} already available"
else
    useradd -u ${service_uid} -g ${service_gid} ${service_user}
    log "${info} User ${service_user} created"
fi

