#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg}

readonly backup_cfg_dir=${etc_dir}/backup

readonly config_file=${backup_cfg_dir}/main.cfg
readonly exclude_file=${backup_cfg_dir}/exclude.cfg
# readonly private_key=${backup_cfg_dir}/id_rsa

readonly log_file=${backup_log}
readonly log_facility="${service}-backup"

. ${scripts_base}/common

if [ ! -f ${private_key} ];then
        log "${critical} Service backup private key ${private_key} missing"
        exit 3
fi
if [ ! -f ${config_file} ];then
        log "${critical} Service backup config ${config_file} missing"
        exit 3
fi
if [ -f ${exclude_file} ];then
    readonly exclude_option="--exclude-from=${exclude_file}"
fi


chmod 600 ${private_key}

if [ -z "$(which rsync)" ]; then
    ${scripts_base}/build/rsync
fi

log "${info} BACKUP STARTED"

# the service is only interested in backing up itself
data_dirs=$(grep data= ${config_file})
#log "${info} Backing-up data..."

readonly rsync_options_line=$(grep rsync_options= ${config_file})
readonly rsync_options=${rsync_options_line##rsync_options=}

line=$(grep backup= ${config_file})
backup_host=$(expr match ${line} "backup=\(.*\):.*:.*:.*")
backup_path=$(expr match ${line} "backup=.*:.*:.*:\(.*\)")
for d in ${data_dirs}; do
    backup_status="${success}"
    dir="$(expr match "${d}" "data=\(.*\)")"
    backup_dest="${backup_host}:${backup_path}/"
    # if ${DIR} does not end in /, we should append it...
    if [ -z "${backup_snapshots}" -o "${backup_snapshots}" != "no" ]; then
	snapshot_dir="/nas/snapshots/${service}/$(date +%Y%m%d)"
	snapshot_opt="--backup --backup-dir=${snapshot_dir}"
    fi
    log "${info} Backup start: ${dir} to ${backup_dest}"

    rsync -av ${rsync_options} -e "ssh -i ${private_key} -o StrictHostKeyChecking=no" ${exclude_option} --delete ${snapshot_opt}  ${dir} ${backup_dest} | logalize ${log_file}
    [ ${PIPESTATUS[0]} -ne 0 ] && backup_status=${critical}
    log "${backup_status} Backup finished: ${dir} to ${backup_dest}"
    # touch ${dir}/.last_vmsbackup
done

log "${info} BACKUP FINISHED"
