#!/bin/bash

readonly scripts_cfg=${0%/scripts*}/etc/scripts.cfg

. ${scripts_cfg}
readonly log_file=${service_log}
readonly log_facility="${service}-keys"
. ${scripts_base}/common

if [ ! -f ${private_key} ]; then
   ssh-keygen -f ${private_key}
   if [ $? -eq 0 ]; then
       log "${success} Keys generated"
   else
       log "${critical} Problem generating keys"
   fi
else
    log "${warning} Keys already available"
fi
