#!/bin/bash

readonly service_cfg=${BASH_SOURCE%/*}/../etc/service.cfg

. ${service_cfg}
readonly log_file=${service_log}
readonly log_facility="${service}-keys"
. ${scripts_base}/common

if [ ! -f ${private_key} ]; then
   if [ ! -d ${key_path} ]; then
       mkdir -p ${key_path}
   fi
   ssh-keygen -f ${private_key}
   if [ $? -eq 0 ]; then
       log "${success} Keys generated"
   else
       log "${critical} Problem generating keys"
   fi
else
    log "${warning} Keys already available"
fi
