#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 

readonly log_file=${service_log}
readonly log_facility="${service}-admin"

. ${scripts_base}/common

. ${etc_dir}/known_hosts

for user in "${!known_hosts[@]}"; do

    if [ -f ${expected_known_hosts[$user]} ]; then
	log "${info} setting up known hosts for ${user}"

	[ ! -d $(dirname ${known_hosts[$user]}) ] && mkdir $(dirname ${known_hosts[$user]})

	if [ ! -f ${known_hosts[$user]} ]; then
	    cp ${expected_known_hosts[$user]} ${known_hosts[$user]} && log "${success} Known hosts set up"
	else
	    log "${info} Known hosts already set up for ${user}"
	fi
    else
	log "${critical} Expected known host ${expected_known_hosts[$user]} not found "
	exit 2
    fi

done
