#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 

readonly log_file=${service_log}
readonly module="slurm"
readonly log_facility="${service}-${module}"
# readonly daemon=${usr_prefix}/slurm/sbin/slurmd
readonly daemon_base=${usr_prefix}/slurm/sbin
readonly pid_file=${data_dir}/slurm/slurmd.pid

. ${scripts_base}/common


slurm_start(){
    log "${info} Starting ${module}"

    if [ ! -f ${daemon} ]; then
	log "${info} Installing slurm"
	${scripts_base}/build/slurm
    fi
    
    # !!!! slurmctld PID is managed by the daemon itself,
    #     slurmd seems not to create it...
    daemon_start ${daemon_base}/slurmctld
    # !!!! slurmd is running as root?
    daemon_start ${daemon_base}/slurmd "-f ${etc_dir}/slurm.conf"
}

slurm_stop(){
    # !!!! kill both daemons properly---
    echo "Doing nothing..."
    # daemon_stop ${pid_file}
}

case "$1" in
    "start")
	slurm_start
	;;
    "stop")
	slurm_stop
	;;
    "restart")
	slurm_stop
	slurm_start
	;;
    *)
	echo "Syntax: $0 [start|stop|restart]"
esac

exit 0
