#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 

readonly log_file=${service_log}
readonly module="squid"
readonly log_facility="${service}-${module}"
readonly daemon=${usr_prefix}/squid/sbin/squid
readonly pid_file=${run_dir}/${module}.pid

. ${scripts_base}/common


squid_start(){
    log "${info} Starting ${module}"

    if [ ! -f ${daemon} ]; then
	log "${info} Installing Squid"
	${scripts_base}/build/squid
    fi

    # !!!! the pid is wrong?
    daemon_start ${daemon} " " ${pid_file}
    # else
#	log "${warning} MySQL already started"
 #   fi
}

squid_stop(){
    # !!!! kill also the nobody child processes...
    daemon_stop ${pid_file}
}

case "$1" in
    "start")
	squid_start
	;;
    "stop")
	squid_stop
	;;
    "restart")
	squid_stop
	squid_start
	;;
    *)
	echo "Syntax: $0 [start|stop|restart]"
esac

exit 0
