#!/bin/bash
# use a custom key with ssh (for example, for git:
# export GIT_SSH="/services/monitoring/scripts/ssh"

readonly scripts_cfg=${0%/scripts*}/etc/scripts.cfg

. ${scripts_cfg} && . ${scripts_base}/common

[ -z ${private_key} ] && readonly private_key=${etc_dir}/service-keys/id_rsa
/usr/bin/ssh -i ${private_key} "$@"
