#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 

readonly log_file=${service_log}
readonly module="sshd"
readonly log_facility="${service}-${module}"
# if service has its own sshd, use it
if [ -x ${usr_prefix}/openssh/sbin/sshd ]; then
    readonly daemon=${usr_prefix}/openssh/sbin/sshd
else
    readonly daemon=/usr/sbin/sshd
fi
readonly pidfile=${run_dir}/${module}.pid
. ${scripts_base}/common


sshd_start(){
    log "${info} Starting ${module}"
    # Pid is managed by sshd itself, as configured in sshd_config
    ${daemon} -p ${ssh_port} -f ${etc_dir}/ssh/sshd_config 
    if [ $? -eq 0 ]; then
	log "${success} ${daemon} started"
    else
	log "${critical} Problem starting ${daemon}"
    fi
}

sshd_stop(){
    log "${info} Stopping ${module}..."
    daemon_stop ${pidfile}
    log "${success} Stopped"
}

case "$1" in
    "start")
	sshd_start
	;;
    "stop")
	sshd_stop
	;;
    "restart")
	sshd_stop
	sshd_start
	;;
    *)
	echo "Syntax: $0 [start|stop|restart]"
esac

exit 0
