#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} 

readonly log_file=${service_log}
readonly module="supervisord"
readonly log_facility="${service}-${module}"
readonly daemon=${usr_prefix}/Python/bin/supervisord


readonly pidfile=${run_dir}/${module}.pid
. ${scripts_base}/common


supervisor_start(){
    log "${info} Starting ${module}"

    [ -z "${user}" ] && readonly user=supervisor
    
    id ${user} > /dev/null
    if [ $? -ne 0 ]; then
	log "${critical} Missing user '${user}'"
	exit 2
    fi

    [ ! -f ${log_dir}/supervisord.log ] && touch ${log_dir}/supervisord.log
    [ ! -f ${pidfile} ] && touch ${pidfile}

    chown ${user} ${pidfile} ${log_dir}/supervisord.log

    ${daemon} -c ${etc_dir}/supervisord.conf
    status=$? ; pid=$!
    if [ ${status} -eq 0 ]; then
	echo ${pid} > ${pidfile}
	log "${success} ${daemon} started"
    else
	log "${critical} Problem starting ${daemon}"
    fi
}

supervisor_stop(){
    log "${info} Stopping ${module}..."
    daemon_stop ${pidfile}
    log "${success} Stopped"
}

case "$1" in
    "start")
	supervisor_start
	;;
    "stop")
	supervisor_stop
	;;
    "restart")
	supervisor_stop
	supervisor_start
	;;
    *)
	echo "Syntax: $0 [start|stop|restart]"
esac

exit 0
