#!/usr/bin/env bash

# @see http://www.linuxfromscratch.org/blfs/view/svn/postlfs/cacerts.html

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg} && . ${scripts_base}/common

# export PATH=${usr_prefix}/pkg-config/bin:${PATH}

[ ! -d "${data_dir}/certs" ] && mkdir -p ${data_dir}/certs
cd ${data_dir}/certs

[ -f certdata.txt ] && rm certdata.txt
wget --no-check-certificate ${nss_certdata} | logalize 
# certdata.txt -> ca-bundle-VERSION.crt
${scripts_base}/make-ca | logalize

# the idea is to update OS certificates,
# therefore we use OS sysconfdir (/etc) instead of ${etc_dir}
cp certs/*.pem /etc/ssl/certs
cp ca-bundle*.crt /etc/ssl/ca-bundle.crt
ln -s /etc/ssl/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt

exit 0

