#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg}
readonly log_file=${service_log}
readonly log_facility="${service}-mysql"
. ${scripts_base}/common

check_params "siteurl" $0 $@

if [ ! $(which mysql) ]; then
    log "${critical} Missing mysql client"
    exit 2
fi

readonly url=$1
readonly wordpress_db=wordpress

log "${info} Updating wordpress settings in DB"

echo "update wp_options set option_value = '${url}' where option_name = 'siteurl';
update wp_options set option_value = '${url}' where option_name = 'home';
" | mysql ${wordpress_db}

if [ $? -eq 0 ]; then
    log "${success} Wordpress settings updated"
else
    log "${critical} Problem updating settings"
fi
