#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg}
readonly log_file=${service_log}
readonly log_facility="${service}"
. ${scripts_base}/common

check_params "login" $0 $@

readonly plain_db=${etc_dir}/rdp-user.txt
readonly berkeley_db=${etc_dir}/rdp-user.db

readonly user=$1

if grep ${user} ${plain_db} > /dev/null; then
    log "${info} User account ${user} already available"
    exit 2
fi

log "${info} Creating xrdp user account ${user}"

# pam_userdb.so typically only supports crypt hash
# in mkpasswd, crypt means DES
# Get password from stdin
readonly cryptpass=$(mkpasswd -s -m des)

echo ${user} >> ${plain_db}
echo ${cryptpass} >> ${plain_db}

# PAM can read root-only files ^_^
chown root.root ${plain_db} ${berkeley_db}
chmod 600 ${plain_db} ${berkeley_db}

db5.1_load -T -t hash -f ${plain_db} ${berkeley_db}

if [ $? -eq 0 ]; then
    log "${success} Xrdp user account ${user} created"
fi
exit 0
