#!/bin/bash

print_usage(){
    echo Create a docker.cfg file
    echo "Syntax: $0 -n container_name"
    exit 1
}


if [ "$#" -gt 0 ]; then
    while getopts "n:" options; do
	case "${options}" in
	    n)
		readonly service=${OPTARG}
		;;
            *)
		echo "Unknow option" 1>&2 
		print_usage
		;;

	esac
    done
    shift $((OPTIND-1))
fi

[ -z "${service}" ] && print_usage

cat <<EOF
readonly container=${service}
EOF
cat <<"EOF"
readonly image=debian:stable-ssh
readonly docker_mounts="-v /services/${container}:/services/${container}:rw"
readonly docker_ports="-p ${http_port}:${http_port} -p ${ssh_port}:22"
readonly container_init="/services/${container}/etc/container-init"
EOF