#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg}

readonly log_file=${service_log}
readonly log_facility="${service}-gf-conf"

. ${scripts_base}/common

readonly etc_guacamole=${etc_dir}/guacamole

[ ! -d ${etc_guacamole} ] && mkdir  ${etc_guacamole}

cat > ${etc_guacamole}/user-mapping.xml <<EOF
<user-mapping>
    <!-- it is possible to use encoding parameter for authorize tag:
            <authorize ... encoding="md5">
    -->
    <authorize username="myuser" password="aa">
        <protocol>vnc</protocol>
        <param name="hostname">localhost</param>
        <param name="port">5901</param>
        <param name="password">aa</param>
    </authorize>

</user-mapping>
EOF

cat > ${etc_guacamole}/guacamole.properties <<EOF
# Hostname and port of guacamole proxy
guacd-hostname: localhost
guacd-port:     4822

# Auth provider class (authenticates user/pass combination, needed if using the provided login screen)
auth-provider: net.sourceforge.guacamole.net.basic.BasicFileAuthenticationProvider
basic-user-mapping: ${etc_dir}/guacamole/user-mapping.xml
EOF

[ "A${guacamole_logging}" == "A1" ] && cat > ${etc_guacamole}/logback.xml <<EOF
<!-- guacamole looks for GUACAMOLE_HOME/logback.xml -->
<configuration>
    <!-- Appender for debugging -->
    <appender name="GUAC-DEBUG" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <!-- Log at DEBUG level. Levels available: error, warn, info, debug -->
    <root level="debug">
        <appender-ref ref="GUAC-DEBUG"/>
    </root>
EOF

log "${info} ${etc_guacamole} set up"

echo "Remember to change passwords in user-mapping.xml"
