#!/bin/bash

if [ $# -ne 1 ]; then
    echo Syntax: $0 service_name
    exit 2
fi

[ -z "${service}" ] && readonly service=$1

readonly service_root=/services/${service}

readonly scripts_base=${service_root}/scripts

readonly data_dir=${service_root}/data
readonly run_dir=${data_dir}/run
readonly etc_dir=${service_root}/etc

readonly log_dir=${service_root}/log
readonly service_log=${log_dir}/service.log
readonly backup_log=${log_dir}/backup.log

readonly usr_prefix=${service_root}/usr
readonly build_dir=${usr_prefix}/src

readonly key_path=${etc_dir}/service-keys
readonly private_key=${key_path}/id_rsa
readonly public_key=${key_path}/id_rsa.pub

readonly web_home=${data_dir}/htdocs

readonly apache_enabled=0
readonly mysql_enabled=0
readonly cron_enabled=1

# other useful variables (under specific circumstances)
# readonly http_port=8040
# readonly default_server=my.server.org
# readonly wordpress_enabled=1
# readonly user=repo
# readonly id=1103
# readonly repo_home=${data_dir}/${user}
