#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg}

readonly log_file=${service_log}
readonly log_facility="${service}-gf-conf"

. ${scripts_base}/common


cat  <<EOF
#%PAM-1.0
# Warning: .db is automatically appended, so the final DB path is...
# ${etc_dir}/rdp-user.db
# Troubleshooting: add "debug" param
auth       required     pam_userdb.so db=${etc_dir}/rdp-user crypt=crypt 
account    required     pam_userdb.so db=${etc_dir}/rdp-user crypt=crypt 
session    required     pam_loginuid.so
EOF


