#!/bin/bash

readonly service_cfg=${0%/scripts*}/etc/service.cfg

. ${service_cfg}

readonly log_file=${service_log}
readonly log_facility="${service}-httpd-conf"

. ${scripts_base}/common

cat <<EOF
# Include these in your service.conf file
   Alias /phpmyadmin ${usr_prefix}/phpmyadmin
   <Directory "${usr_prefix}/phpmyadmin">
       DirectoryIndex index.php
       Require all granted
   </Directory>
EOF
